### ISSUE TITLE
Force RAM value to float

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/osm2pgsql-tuner#14]
# Details

Current code fails unexpectedly if the project calling decides the value is an `int` instead of a `float`, adjusted https://github.com/rustprooflabs/pgosm-flex/pull/204 to work around.  That should be fixed here.

**Comment by rustprooflabs** [comment]
Not a bug here.  Couldn't reproduce immediately with a quick test.  Removing the `--float` definition from PgOSM Flex does reproduce what I saw yesterday.

```
2021-11-13 07:29:14,373:INFO:pgosm-flex:osm2pgsql_recommendation:PBF size (GB): 0.016382375732064247
Traceback (most recent call last):
  File "/app/docker/pgosm_flex.py", line 717, in <module>
    run_pgosm_flex()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/docker/pgosm_flex.py", line 115, in run_pgosm_flex
    osm2pgsql_command = get_osm2pgsql_command(region=region,
  File "/app/docker/pgosm_flex.py", line 622, in get_osm2pgsql_command
    rec_cmd = rec.osm2pgsql_recommendation(ram=ram,
  File "/app/docker/osm2pgsql_recommendation.py", line 43, in osm2pgsql_recommendation
    osm2pgsql_cmd = get_recommended_script(system_ram_gb,
  File "/app/docker/osm2pgsql_recommendation.py", line 79, in get_recommended_script
    rec = tuner.recommendation(system_ram_gb=system_ram_gb,
  File "/usr/local/lib/python3.9/dist-packages/osm2pgsql_tuner/tuner.py", line 42, in __init__
    self.osm2pgsql_cache_max = self._calculate_max_osm2pgsql_cache()
  File "/usr/local/lib/python3.9/dist-packages/osm2pgsql_tuner/tuner.py", line 143, in _calculate_max_osm2pgsql_cache
    osm2pgsql_cache_max = self.system_ram_gb * 0.66
TypeError: can't multiply sequence by non-int of type 'float'
```

I thought I saw it say "can't multiple int by... " but it doesn't.  This was a problem only with how the parameter via click was set w/out the explicit `--type=float` option added.
